---
title: "RStudio Recap"
author: "Heili Lowman"
date: "9/1/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Data & Packages

To insert a new code chunk:
 -   Mac - cmd + opt + I
 -   PC - ctrl + alt + I

```{r packages}

# Load necessary packages.
library(tidyverse)

```

```{r data}

# Load in our dataset.
#data_set <- read_csv("my_data.csv")

# Call built-in dataset.
lynx_data <- lynx

# Examine data.
#View(lynx_data)

```

## Data Tidying

```{r tidy}

# Examine structure.
#str(lynx_data)

# Make my data *not* a time series.
library(timetk)
lynx_df <- tk_tbl(lynx_data)
#View(lynx_df)

# Change column names.
lynx_df <- lynx_df %>% # Base dataset.
  rename(Year = index, Lynx = value) # Renames columns.

# Changing column structure.
# as.numeric() - coerces column to be numeric, force all non-numeric values to be "NA"
# as.character()
# as.factor() - also a text string, but can be categorical/ordinal
# relevel() - relevel factors in a particular order

# naniar() - good package for dealing with NAs, opposite of replace_na()
# replace_NA() - replacing NAs with specified values

# Ellie's question/answer:
#dataset <- dataset %>%
#  mutate(new_column = as.numeric(old_columnn))

```

## Data Visualization

```{r plot}

# Create a basic scatterplot of my lynx trapping data.
lynx_fig <- ggplot(lynx_df, aes(x = Year, y =Lynx)) + # basic dataset
  geom_point(size = 3, alpha = 0.75) + # creates scatterplot
  geom_smooth(method = lm, color = "aquamarine2") + # adds linear model
  labs(x = "Year",
    y = "Number of Lynx Trapped",
    title = "Lynx R Dataset",
    subtitle = "Tidy Tuesday demo, September 1",
    caption = "Data Source: Brockwell and Davis 1991") + # includes labels
  theme_classic() + # theme with only axes present
  theme(legend.position = "none") + # suppresses legend
  scale_x_continuous(breaks = seq(1820, 1940, 10)) # edits x axes tick marks
  
lynx_fig # Calls figure.  
  
# commenting out shortcut:
# Mac: Command + Shift + C
# PC: Ctrl + Shift + C
# leah_fig <- orig_data %>% # original dataset
#   filter(column == "A") %>% # operations
#   ggplot(aes()) + # close plot

# Create boxplot with raw data values showing:
# ggplot(data, aes(x = x, y = y))+
#   geom_boxplot() +
#   geom_jitter() 
#   geom_hline()
#   geom_vline()
  

```

End of RMarkdown script.